import './globals.css';

import Header from './Header';

import styles from './layout.module.css';
import { dmMono } from '../styles/fonts';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={dmMono.className}>
        <Header />
        <main className={styles.main}>{children}</main>
      </body>
    </html>
  );
}
